### ISSUE TITLE
Exception after updating to CNeptune 1.1.0

### ISSUE THREAD

**Issue by jho1965us** [Virtuoze/CNeptune#8]
2>------ Build started: Project: Outliner, Configuration: Debug Any CPU ------
2>  Outliner -> C:\Users\xx\Documents\Visual Studio 2017\Projects\yy\Outliner\bin\Debug\Outliner.dll
2>  
2>  Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
2>     at Mono.Collections.Generic.Collection`1.get_Item(Int32 index)
2>     at CNeptune.Program.Manage(MethodDefinition method)
2>     at CNeptune.Program.Manage(TypeDefinition type)
2>     at CNeptune.Program.Manage(String assembly)
2>     at CNeptune.Program.Main(String[] arguments)
2>C:\Users\xx\Documents\Visual Studio 2017\Projects\yy\packages\CNeptune.1.1.0\build\CNeptune.targets(10,9): error MSB3073: The command ""C:\Users\xx\Documents\Visual Studio 2017\Projects\yy\packages\CNeptune.1.1.0\build\CNeptune.exe" "C:\Users\xx\Documents\Visual Studio 2017\Projects\yy\Outliner\Outliner.csproj" "Debug"" exited with code -532462766.

Outliner.csproj OutputType = Library

**Comment by Virtuoze** [comment]
Hi, I found this issue yesterday while I am testing async Interception.

There is a wrong argument offset in last release using OpCodes.Ldarg_S.
I used to write Emit(Ldarg_S, index) to emit argument at good position with Reflection Emit API from Microsoft. But when it failed on Mono.Cecil, I just translate it as Emit(OpCodes.Ldarg_S, parameters[index]) missing fact that method can be static or instance method. In case of Instance method, it need to be parameters[index - 1]. The code throw an index of of range exception if method have more than 2 arguments 👎 .

bug is on line 212 of this file : [https://github.com/Virtuoze/Neptune/blob/master/Framework/Injection/Program.cs](https://github.com/Virtuoze/Neptune/blob/master/Framework/Injection/Program.cs)

It is already fixed locally for next version that will be publish in few days.
Thank you for your interest,

Best regards

**Comment by jho1965us** [comment]
Still a problem in v1.2.0

not sure if the loop should be over method.Parameters or _authentic.Parameters but surely it must be the same variable before Parameters

```
namespace CNeptune 
    static public class Program
         ...
        static private void Manage(this MethodDefinition method)
            ...
            for (var _index = 0; _index < _authentic.Parameters.Count; _index++)
                switch (_index)
                   ...
                   default: method.Body.Emit(OpCodes.Ldarg_S, method.Parameters[_index]); break;

```
Note: the code that fails is a constructor with 4 parameters i.e. 5 parameters in _authentic

**Comment by Puresharper** [comment]
Hi, sorry fix is not in 1.2.0.
Fortunately, I just test it and patch it in 1.2.1

**Comment by Puresharper** [comment]
NConcern was just updated to 4.1.0 to ignore framework assembly when lookup joinpoint

**Comment by jho1965us** [comment]
Thanks, Seems to work now I have a runtime problem but that seems unrelated I have created a new issue
